services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8080:8080"

  ui:
    build:
      context: .
      dockerfile: docker/ui/Dockerfile
    depends_on:
      - api
    environment:
      API_URL: http://api:8080
    stdin_open: true
    tty: true
